<<<<<<< HEAD
settings:
  debug: false
defaults:
  tax: 10
phrases:
  town_no_exist: 'Town \"%town\" does not exist.'
  item_no_exist: 'Item \"%item\" does not exist.'
  invalid_quantity: 'Invalid quantity.'
  sign_created: 'Shop created!'
=======
defaults:
  tax: 10
>>>>>>> f0cdb11a47cc4b17f0d6430b8de97ebe1ba87bf6
